config/routes.rb
Rails.application.routes.draw do
  resources :absents
  resources :rationales
  resources :teachers
  resources :classrooms
  resources :kids
  devise_for :users, :skip => [:sessions]

  as :user do
    get 'login' => "devise/sessions#new", :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'kids#index'

post "kids/print_food_restrictions_list" => "kids#print_food_restrictions_list"
post "kids/print_allergy_list" => "kids#print_allergy_list"
post "kids/print_special_med_alerts_list" => "kids#print_special_med_alerts_list"
post "kids/print_special_alerts_list" => "kids#print_special_alerts_list"
post "kids/print_student_list" => "kids#print_student_list"
post "kids/print_teacher_list" => "kids#print_teacher_list"
post "kids/print_email_list" => "kids#print_email_list"
post "kids/print_welcome_package" => "kids#print_welcome_package"
post "kids/print_infant_wp_package" => "kids#print_infant_wp_package"
post "kids/print_attendance" => "kids#print_attendance"
post "kids/print_attendance_two" => "kids#print_attendance_two"
post "kids/print_class_summary" => "kids#print_class_summary"
post "kids/print_upcoming_flips_report" => "kids#print_upcoming_flips_report"
post "kids/print_anaphylactic_form" => "kids#print_anaphylactic_form"
get "kids/:id/print_enrolment_completed" => "kids#print_enrolment_completed"
get "kids/:id/print_15_absent_day_letter" => "kids#print_15_absent_day_letter"
get "kids/:id/print_after_july_1st_letter" => "kids#print_after_july_1st_letter"
get "kids/:id/print_20_consecutive_absent_day_letter" => "kids#print_20_consecutive_absent_day_letter"
get "kids/:id/print_25_absent_day_letter" => "kids#print_25_absent_day_letter"
get "kids/:id/print_33_absent_day_letter" => "kids#print_33_absent_day_letter"
get "kids/:id/print_35_absent_day_letter" => "kids#print_35_absent_day_letter"
get "kids/:id/print_student_review_letter" => "kids#print_student_review_letter"

get "teachers/:id/destroy" => "teachers#destroy"

resources :kids do
  get 'discharge', on: :member
end
resources :kids do
  get 'restore', on: :member
end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	has_many :teachers
	has_many :kids
	belongs_to :user
	
	def allergies_report 
		allergies = []
		kids.where(discharge_date: nil).where.not(allergy_description_one: [nil, '']).each do |kid|
			for i in 1..5
				if kid.send("allergy_description_#{in_words(i)}").present?
					allergies << {full_name: kid.first_name + ' ' + kid.last_name, description: kid.send("allergy_description_#{in_words(i)}"), 
					medication: kid.send("allergy_medication_#{in_words(i)}"),	symptoms: kid.send("allergy_symptoms_#{in_words(i)}"), 
					expiry: kid.send("allergy_expiry_#{in_words(i)}"), actions: kid.send("allergy_actions_#{in_words(i)}"), 
					epipen: kid.send("allergy_epipen_#{in_words(i)}") }
				end
			end	
		end
		return allergies
	end
	def food_rest_report
		food = []
		kids.where(discharge_date: nil).where.not(food_description_one: [nil, '']).each do |kid|
			for i in 1..5
				if kid.send("food_description_#{in_words(i)}").present?
					food << {full_name: kid.first_name + ' ' + kid.last_name, description: kid.send("food_description_#{in_words(i)}"), 
					medication: kid.send("food_medication_#{in_words(i)}"),	symptoms: kid.send("food_symptoms_#{in_words(i)}"), 
					expiry: kid.send("food_expiry_#{in_words(i)}"), actions: kid.send("food_actions_#{in_words(i)}"), 
					epipen: kid.send("food_epipen_#{in_words(i)}") }
				end
			end	
		end
		return food
	end	
	def kids_with_special_med_alerts
		kids.where(discharge_date: nil).where.not("special_med_description_one = ? and special_med_description_one = ?", nil, '')
	end
	def kids_with_special_alerts
		kids.where(discharge_date: nil).where.not(special_alerts: '')
	end

	def in_words(num)
		if num == 1
			return "one"
		elsif num == 2
			return "two"
		elsif num == 3
			return "three"
		elsif num == 4
			return "four"
		elsif num == 5
			return "five"
		end
	end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @user ||= current_user
    if current_user.admin?
      @classrooms = Classroom.all
    else
      @classrooms = @user.classrooms.all
    end  
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  	classroom = Classroom.find(params[:id])
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)
    respond_to do |format|
      if @classroom.save
        format.html { redirect_to root_url, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to root_url, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit!
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_addmodal.html.erb
<%= form_for(classroom, :html => {class: "form-horizontal", autocomplete: "off" }) do |f| %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4>Add Classroom</h4>
</div>
<div class="modal-body">
  <p>Please contact support to add Full Fee Rate if this is a distintively new age group.</p>
  <br>
  <div class="form-group">
    <%= f.label :class_name, "Class Name", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :class_name, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :capacity, class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :capacity, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :start_range, "Start Range (months)", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :start_range, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :end_range, "End Range (months)", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :end_range, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :user_id, "Daycare Location", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.select :user_id, @users_wo_admin.all.collect {|a| [a.daycare_location, a.id]}, {}, {class: "form-control" } %>
    </div>
  </div>
  

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/classrooms/_classmodal.html.erb
<h4>Teachers Assigned</h4>
         <ol>
          <% classroom.teachers.each do |teacher| %>
            <li><%= teacher.first_name %> <%= teacher.last_name %></li>
          <% end %>          
         </ol>
        <br>
        <h4>Students</h4>
          <ol>
          <% classroom.kids.where(discharge_date: nil).each do |kid| %>
            <li><%= kid.first_name %> <%= kid.last_name %>
	    <% if kid.ba? %> - B&A <% end %>
		</li>
          <% end %>          
         </ol>  

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @classroom.kids.where(discharge_date: nil).count > 0 or @classroom.teachers.count > 0 %>
    <p>If you are trying to rename the classroom, please create a new classroom (from an Admin account) and then move all students and teachers to that classroom. Please note that classrooms cannot be renamed/deleted if there are still students and teachers assigned to the classroom, as it causes the system to crash. In order rename/delete this classroom please move all students and teachers first. </p><br>
  <% elsif @classroom.kids.where(discharge_date: nil).count == 0 and @classroom.teachers.count == 0 and current_user.admin? == false %>
    <p>Please login to an Admin account to delete this classroom.</p>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :start_range, "Start range (months)" %><br>
    <%= f.number_field :start_range %>
  </div>
  <div class="field">
    <%= f.label :end_range, "End range (months)" %><br>
    <%= f.number_field :end_range %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <% if @classroom.kids.where(discharge_date: nil).count == 0 and @classroom.teachers.count == 0 and current_user.admin? %> 
      <%= button_to 'Delete Class', @classroom, method: :delete, data: { confirm: 'Are you sure? This action cannot be undone.' }, class: "btn btn-danger" %>
    <% else %>
      <%= button_to 'Delete Class', @classroom, method: :delete, data: { confirm: 'Are you sure? This action cannot be undone.' }, class: "btn btn-danger", disabled: true  %>
    <% end %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.class_name %></td>
        <td><%= classroom.capacity %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @classroom.class_name %>
</p>


<p>
  <strong>Capacity:</strong>
  <%= @classroom.capacity %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>