config/routes.rb
Rails.application.routes.draw do
  resources :absents
  resources :rationales
  resources :teachers
  resources :classrooms
  resources :kids
  devise_for :users, :skip => [:sessions]

  as :user do
    get 'login' => "devise/sessions#new", :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'kids#index'

post "kids/print_food_restrictions_list" => "kids#print_food_restrictions_list"
post "kids/print_allergy_list" => "kids#print_allergy_list"
post "kids/print_special_med_alerts_list" => "kids#print_special_med_alerts_list"
post "kids/print_special_alerts_list" => "kids#print_special_alerts_list"
post "kids/print_student_list" => "kids#print_student_list"
post "kids/print_teacher_list" => "kids#print_teacher_list"
post "kids/print_email_list" => "kids#print_email_list"
post "kids/print_welcome_package" => "kids#print_welcome_package"
post "kids/print_infant_wp_package" => "kids#print_infant_wp_package"
post "kids/print_attendance" => "kids#print_attendance"
post "kids/print_attendance_two" => "kids#print_attendance_two"
post "kids/print_class_summary" => "kids#print_class_summary"
post "kids/print_upcoming_flips_report" => "kids#print_upcoming_flips_report"
post "kids/print_anaphylactic_form" => "kids#print_anaphylactic_form"
get "kids/:id/print_enrolment_completed" => "kids#print_enrolment_completed"
get "kids/:id/print_15_absent_day_letter" => "kids#print_15_absent_day_letter"
get "kids/:id/print_after_july_1st_letter" => "kids#print_after_july_1st_letter"
get "kids/:id/print_20_consecutive_absent_day_letter" => "kids#print_20_consecutive_absent_day_letter"
get "kids/:id/print_25_absent_day_letter" => "kids#print_25_absent_day_letter"
get "kids/:id/print_33_absent_day_letter" => "kids#print_33_absent_day_letter"
get "kids/:id/print_35_absent_day_letter" => "kids#print_35_absent_day_letter"
get "kids/:id/print_student_review_letter" => "kids#print_student_review_letter"

get "teachers/:id/destroy" => "teachers#destroy"

resources :kids do
  get 'discharge', on: :member
end
resources :kids do
  get 'restore', on: :member
end

end

app/models/rationale.rb
class Rationale < ActiveRecord::Base
	belongs_to :user
end

app/controllers/rationales_controller.rb
class RationalesController < ApplicationController
  before_action :set_rationale, only: [:show, :edit, :update, :destroy]

  # GET /rationales
  # GET /rationales.json
  def index
    @rationales = Rationale.all.order('created_at DESC')
  end

  # GET /rationales/1
  # GET /rationales/1.json
  def show
  end

  # GET /rationales/new
  def new
    @rationale = Rationale.new
  end

  # GET /rationales/1/edit
  def edit
  end

  # POST /rationales
  # POST /rationales.json
  def create
    @rationale = Rationale.new(rationale_params)
    @rationale.user = current_user
    respond_to do |format|
      if @rationale.save
        format.html { head :no_content }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @rationale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rationales/1
  # PATCH/PUT /rationales/1.json
  def update
    respond_to do |format|
      if @rationale.update(rationale_params)
        format.html { redirect_to @rationale, notice: 'Rationale was successfully updated.' }
        format.json { render :show, status: :ok, location: @rationale }
      else
        format.html { render :edit }
        format.json { render json: @rationale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rationales/1
  # DELETE /rationales/1.json
  def destroy
    @rationale.destroy
    respond_to do |format|
      format.html { redirect_to rationales_url, notice: 'Rationale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rationale
      @rationale = Rationale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rationale_params
      params.fetch(:rationale, {})
      params.require(:rationale).permit!
    end
end

app/helpers/rationales_helper.rb
module RationalesHelper
end

app/views/rationales/_form.html.erb
<%= form_for(@rationale) do |f| %>
  <% if @rationale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rationale.errors.count, "error") %> prohibited this rationale from being saved:</h2>

      <ul>
      <% @rationale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rationales/edit.html.erb
<h1>Editing Rationale</h1>

<%= render 'form' %>

<%= link_to 'Show', @rationale %> |
<%= link_to 'Back', rationales_path %>

app/views/rationales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Edits Made</h1>

<table>
  <thead>
    <tr>
      <th>Edit Date</th>    
      <th>Daycare</th>
      <th>Student Edited</th>
      <th>Edited By</th>
      <th>Rationale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rationales.each do |rationale| %>
      <tr>
        <td><%= rationale.created_at %></td>
        <td><%= rationale.user.daycare_location %></td>
        <td><%= rationale.child_name %></td>
        <td><%= rationale.full_name %></td>
        <td><%= rationale.rational %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<style>
td
{
    padding:5px 20px 5px 20px;
}
th
{
    padding:0 20px 0 20px;
}
</style>


<%= link_to 'Back', kids_path %>

app/views/rationales/new.html.erb
<h1>New Rationale</h1>

<%= render 'form' %>

<%= link_to 'Back', rationales_path %>

app/views/rationales/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rationale_path(@rationale) %> |
<%= link_to 'Back', rationales_path %>