config/routes.rb
Rails.application.routes.draw do
  resources :absents
  resources :rationales
  resources :teachers
  resources :classrooms
  resources :kids
  devise_for :users, :skip => [:sessions]

  as :user do
    get 'login' => "devise/sessions#new", :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'kids#index'

post "kids/print_food_restrictions_list" => "kids#print_food_restrictions_list"
post "kids/print_allergy_list" => "kids#print_allergy_list"
post "kids/print_special_med_alerts_list" => "kids#print_special_med_alerts_list"
post "kids/print_special_alerts_list" => "kids#print_special_alerts_list"
post "kids/print_student_list" => "kids#print_student_list"
post "kids/print_teacher_list" => "kids#print_teacher_list"
post "kids/print_email_list" => "kids#print_email_list"
post "kids/print_welcome_package" => "kids#print_welcome_package"
post "kids/print_infant_wp_package" => "kids#print_infant_wp_package"
post "kids/print_attendance" => "kids#print_attendance"
post "kids/print_attendance_two" => "kids#print_attendance_two"
post "kids/print_class_summary" => "kids#print_class_summary"
post "kids/print_upcoming_flips_report" => "kids#print_upcoming_flips_report"
post "kids/print_anaphylactic_form" => "kids#print_anaphylactic_form"
get "kids/:id/print_enrolment_completed" => "kids#print_enrolment_completed"
get "kids/:id/print_15_absent_day_letter" => "kids#print_15_absent_day_letter"
get "kids/:id/print_after_july_1st_letter" => "kids#print_after_july_1st_letter"
get "kids/:id/print_20_consecutive_absent_day_letter" => "kids#print_20_consecutive_absent_day_letter"
get "kids/:id/print_25_absent_day_letter" => "kids#print_25_absent_day_letter"
get "kids/:id/print_33_absent_day_letter" => "kids#print_33_absent_day_letter"
get "kids/:id/print_35_absent_day_letter" => "kids#print_35_absent_day_letter"
get "kids/:id/print_student_review_letter" => "kids#print_student_review_letter"

get "teachers/:id/destroy" => "teachers#destroy"

resources :kids do
  get 'discharge', on: :member
end
resources :kids do
  get 'restore', on: :member
end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :classroom
	belongs_to :user
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    teacher = Teacher.find(params[:id])
    respond_to do |format|
      format.html { render action: 'show' }
      format.json do
      # Return kid as json object
      result = teacher.attributes.to_json 
      render json: result
    end
  end
end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
    @user ||= current_user
    @classrooms = @user.classrooms.all
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to root_url, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to root_url, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit!
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_addmodal.html.erb
<%= form_for(teacher, :html => {class: "form-horizontal", autocomplete: "off" }) do |f| %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4>Add Teacher</h4>
</div>
<div class="modal-body">
  <br>
  <div class="form-group">
    <%= f.label :first_name, "First Name", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :first_name, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Last Name", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :employee_id, "Employee ID", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :employee_id, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone, class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :alt_phone, "Alternate Phone", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.text_field :alt_phone, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.select :title, options_for_select(["RECE", "Student", "Assistant", "P/T Assistant", "Supply", "Kitchen Staff", "Supervisor"]), {include_blank: true}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :classroom_id, "Class Name", class: "col-lg-3 control-label" %>
    <div class="col-lg-9">
      <%= f.select :classroom_id, options_from_collection_for_select(@classrooms, 'id', 
        'class_name'), {include_blank: "N/A"}, {class: "form-control" } %>
    </div>
  </div>

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.text_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :alt_phone, "Alternate Phone" %><br>
    <%= f.text_field :alt_phone %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.select :title, options_for_select(["RECE", "Student", "Assistant", "P/T Assistant", "Supply", "Kitchen Staff", "Supervisor"], selected: f.object.title), {include_blank: true} %>
  </div>
  <div class="field">
      <%= f.label :classroom_id, "Class Name" %>
      <%= f.select :classroom_id, options_from_collection_for_select(@classrooms, 'id', 'class_name', selected: f.object.classroom_id), include_blank: "N/A" %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Employee</th>
      <th>Class name</th>
      <th>Class desc</th>
      <th>Class size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.employee_id %></td>
        <td><%= teacher.class_name %></td>
        <td><%= teacher.class_desc %></td>
        <td><%= teacher.class_size %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @teacher.employee_id %>
</p>

<p>
  <strong>Class name:</strong>
  <%= @teacher.class_name %>
</p>

<p>
  <strong>Class desc:</strong>
  <%= @teacher.class_desc %>
</p>

<p>
  <strong>Class size:</strong>
  <%= @teacher.class_size %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>