config/routes.rb
Rails.application.routes.draw do
  resources :absents
  resources :rationales
  resources :teachers
  resources :classrooms
  resources :kids
  devise_for :users, :skip => [:sessions]

  as :user do
    get 'login' => "devise/sessions#new", :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'kids#index'

post "kids/print_food_restrictions_list" => "kids#print_food_restrictions_list"
post "kids/print_allergy_list" => "kids#print_allergy_list"
post "kids/print_special_med_alerts_list" => "kids#print_special_med_alerts_list"
post "kids/print_special_alerts_list" => "kids#print_special_alerts_list"
post "kids/print_student_list" => "kids#print_student_list"
post "kids/print_teacher_list" => "kids#print_teacher_list"
post "kids/print_email_list" => "kids#print_email_list"
post "kids/print_welcome_package" => "kids#print_welcome_package"
post "kids/print_infant_wp_package" => "kids#print_infant_wp_package"
post "kids/print_attendance" => "kids#print_attendance"
post "kids/print_attendance_two" => "kids#print_attendance_two"
post "kids/print_class_summary" => "kids#print_class_summary"
post "kids/print_upcoming_flips_report" => "kids#print_upcoming_flips_report"
post "kids/print_anaphylactic_form" => "kids#print_anaphylactic_form"
get "kids/:id/print_enrolment_completed" => "kids#print_enrolment_completed"
get "kids/:id/print_15_absent_day_letter" => "kids#print_15_absent_day_letter"
get "kids/:id/print_after_july_1st_letter" => "kids#print_after_july_1st_letter"
get "kids/:id/print_20_consecutive_absent_day_letter" => "kids#print_20_consecutive_absent_day_letter"
get "kids/:id/print_25_absent_day_letter" => "kids#print_25_absent_day_letter"
get "kids/:id/print_33_absent_day_letter" => "kids#print_33_absent_day_letter"
get "kids/:id/print_35_absent_day_letter" => "kids#print_35_absent_day_letter"
get "kids/:id/print_student_review_letter" => "kids#print_student_review_letter"

get "teachers/:id/destroy" => "teachers#destroy"

resources :kids do
  get 'discharge', on: :member
end
resources :kids do
  get 'restore', on: :member
end

end

app/models/absent.rb
class Absent < ActiveRecord::Base
	belongs_to :kid
end

app/controllers/absents_controller.rb
class AbsentsController < ApplicationController
  before_action :set_absent, only: [:show, :edit, :update, :destroy]

  # GET /absents
  # GET /absents.json
  def index
    @absents = Absent.all
  end

  # GET /absents/1
  # GET /absents/1.json
  def show
  end

  # GET /absents/new
  def new
    @absent = Absent.new
  end

  # GET /absents/1/edit
  def edit
  end

  # POST /absents
  # POST /absents.json
  def create
    @absent = Absent.new(absent_params)

    respond_to do |format|
      if @absent.save
        format.html { redirect_to root_url, notice: 'Absent was successfully created.' }
        format.json { render :show, status: :created, location: @absent }
      else
        format.html { render :new }
        format.json { render json: @absent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /absents/1
  # PATCH/PUT /absents/1.json
  def update
    respond_to do |format|
      if @absent.update(absent_params)
        format.html { redirect_to @absent, notice: 'Absent was successfully updated.' }
        format.json { render :show, status: :ok, location: @absent }
      else
        format.html { render :edit }
        format.json { render json: @absent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /absents/1
  # DELETE /absents/1.json
  def destroy
    @absent.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Absent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_absent
      @absent = Absent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def absent_params
      params.require(:absent).permit!
    end
end

app/helpers/absents_helper.rb
module AbsentsHelper
end

app/views/absents/_form.html.erb
<%= form_for(@absent) do |f| %>
  <% if @absent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@absent.errors.count, "error") %> prohibited this absent from being saved:</h2>

      <ul>
      <% @absent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/absents/edit.html.erb
<h1>Editing Absent</h1>

<%= render 'form' %>

<%= link_to 'Show', @absent %> |
<%= link_to 'Back', absents_path %>

app/views/absents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Absents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @absents.each do |absent| %>
      <tr>
        <td><%= link_to 'Show', absent %></td>
        <td><%= link_to 'Edit', edit_absent_path(absent) %></td>
        <td><%= link_to 'Destroy', absent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Absent', new_absent_path %>

app/views/absents/new.html.erb
<h1>New Absent</h1>

<%= render 'form' %>

<%= link_to 'Back', absents_path %>

app/views/absents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @absent.date %>
</p>

<%= link_to 'Edit', edit_absent_path(@absent) %> |
<%= link_to 'Back', absents_path %>